[package]
name = "quick-look"
version = "1.0.0"
description = "Quickly view a file."
authors = ["poohlaha"]
license = "MIT/Apache-2.0"
repository = "tgithub.com/poohlaha/quick-look"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-alpha", features = [] }

[dependencies]
log = "0.4"
thiserror = "1.0"
base64 = "0.21"
urlencoding = "2.1"
zip = "0.6"
chrono = "0.4"
flate2 = "1.0"
tar = "0.4"
dirs = "5.0"
unrar = "0.4"
xz2 = "0.1"
bzip2 = "0.4"
encoding_rs = "0.8"
sevenz-rust = "0.5"
tauri-plugin-log = "2.0.0-alpha"
tauri-plugin-dialog = "2.0.0-alpha"
tauri = { version = "2.0.0-alpha", features = [] }
tauri-plugin-window = "2.0.0-alpha"
tauri-plugin-shell = "2.0.0-alpha"
serde_json = "1.0"
serde = { version = "1.0.193", features = ["derive"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
