[package]
name = "quick-look"
version = "1.0.0"
description = "Quickly view a file."
authors = ["poohlaha"]
license = "MIT/Apache-2.0"
repository = "https://github.com/poohlaha/quick-look"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-alpha", features = [] }

[dependencies]
log = "0.4"
thiserror = "1.0"
base64 = "0.21"
urlencoding = "2.1"
zip = "0.6"
chrono = "0.4"
flate2 = "1.0"
tar = "0.4"
dirs = "5.0"
unrar = "0.4"
xz2 = "0.1"
bzip2 = "0.4"
encoding_rs = "0.8"
sevenz-rust = "0.5"
fs_extra = "1.3"
mupdf = "0.4"
crypto-hash = "0.3"
tauri-plugin-log = "2.0.0-alpha"
tauri-plugin-dialog = "2.0.0-alpha"
tauri = { version = "2.0.0-alpha", features = ["tray-icon", "icon-png"] }
tauri-plugin-window = "2.0.0-alpha"
tauri-plugin-shell = "2.0.0-alpha"
serde_json = "1.0"
serde = { version = "1.0.193", features = ["derive"] }

[dependencies.uuid]
version = "1.4.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
